### ISSUE TITLE
Different configs for production and development server

### ISSUE THREAD

**Issue by janstieler** [bartvandebiezen/kirby-v2-scssphp#7]
Hi,

what exactly do the scssNestedCheck config value?
And how can I disable the SCSSplugin on a productionserver, or is this not necessary?
I use different configfiles. One for my development server and one for the productionserver.

Cheers

**Comment by bartvandebiezen** [comment]
Hi Jan, the scssNestedCheck checks if any SCSS partial file is updated and updates the CSS file if needed. Because this is great when you are developing, but somewhat CPU intensive, I advice to only turn this on for your dev environment. When turned off, the plugin only checks if the default.scss is up to date.

**Comment by janstieler** [comment]
Hi Bart, 
thanks for the explanation. It helps me on.
